exports.cats = {
    APPLICATION: ('APPLICATION', 'Application'),
    ANDROID_WEAR: ('ANDROID_WEAR', 'Android Wear'),
    ART_AND_DESIGN: ('ART_AND_DESIGN', 'Art & Design'),
    AUTO_AND_VEHICLES: ('AUTO_AND_VEHICLES', 'Auto & Vehicles'),
    BEAUTY: ('BEAUTY', 'Beauty'),
    BOOKS_AND_REFERENCE: ('BOOKS_AND_REFERENCE', 'Books & Reference'),
    BUSINESS: ('BUSINESS', 'Business'),
    COMICS: ('COMICS', 'Comics'),
    COMMUNICATION: ('COMMUNICATION', 'Communication'),
    DATING: ('DATING', 'Dating'),
    EDUCATION: ('EDUCATION', 'Education'),
    ENTERTAINMENT: ('ENTERTAINMENT', 'Entertainment'),
    EVENTS: ('EVENTS', 'Events'),
    FINANCE: ('FINANCE', 'Finance'),
    FOOD_AND_DRINK: ('FOOD_AND_DRINK', 'Food & Drink'),
    HEALTH_AND_FITNESS: ('HEALTH_AND_FITNESS', 'Health & Fitness'),
    HOUSE_AND_HOME: ('HOUSE_AND_HOME', 'House & Home'),
    LIBRARIES_AND_DEMO: ('LIBRARIES_AND_DEMO', 'Libraries & Demo'),
    LIFESTYLE: ('LIFESTYLE', 'Lifestyle'),
    MAPS_AND_NAVIGATION: ('MAPS_AND_NAVIGATION', 'Maps & Navigation'),
    MEDICAL: ('MEDICAL', 'Medical'),
    MUSIC_AND_AUDIO: ('MUSIC_AND_AUDIO', 'Music & Audio'),
    NEWS_AND_MAGAZINES: ('NEWS_AND_MAGAZINES', 'News & Magazines'),
    PARENTING: ('PARENTING', 'Parenting'),
    PERSONALIZATION: ('PERSONALIZATION', 'Personalization'),
    PHOTOGRAPHY: ('PHOTOGRAPHY', 'Photography'),
    PRODUCTIVITY: ('PRODUCTIVITY', 'Productivity'),
    SHOPPING: ('SHOPPING', 'Shopping'),
    SOCIAL: ('SOCIAL', 'Social'),
    SPORTS: ('SPORTS', 'Sports'),
    TOOLS: ('TOOLS', 'Tools'),
    TRAVEL_AND_LOCAL: ('TRAVEL_AND_LOCAL', 'Travel & Local'),
    VIDEO_PLAYERS: ('VIDEO_PLAYERS', 'Video Players'),
    WEATHER: ('WEATHER', 'Weather'),
    GAME: ('GAME', 'Games'),
    FAMILY: ('FAMILY', 'Family'),
  };